print("Integer Calculator")
num1 = int(input("Enter a number : "))
num2 = int(input("Enter a number again : "))
print(f"The sum of the numbers are : {num1 + num2}")
print(f"The sum of the numbers are : {num1 - num2}")
print(f"The sum of the numbers are : {num1 * num2}")
print(f"The sum of the numbers are : {num1 ** num2}")
print(f"The sum of the numbers are : {num1 / num2}")
print(f"The sum of the numbers are : {num1 // num2}")